// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AccessToken string
	Name        string
	Username    string
	GithubID    int32
	Repos       int32
	Email       string
	PanelBody   sql.NullString
	Role        sql.NullString
	AvatarUrl   string
}
