// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleFullstack UserRole = "Fullstack"
	UserRoleFrontend  UserRole = "Frontend"
	UserRoleBackend   UserRole = "Backend"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Collab struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	User1GithubID int32
	User2GithubID int32
	Message       sql.NullString
	Pending       bool
}

type Language struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Color     string
}

type Repo struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	UserGithubID  int32
	StarGazers    int32
	Watchers      int32
	Url           string
	RepoCreatedAt time.Time
	RepoUpdatedAt time.Time
}

type ReposLanguage struct {
	ID         uuid.UUID
	RepoID     uuid.UUID
	LanguageID uuid.UUID
	Bytes      int32
}

type User struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	GithubCreatedAt time.Time
	AccessToken     string
	Name            string
	Username        string
	GithubID        int32
	Email           string
	Followers       int32
	Following       int32
	PanelBody       sql.NullString
	Role            UserRole
	AvatarUrl       string
	Location        string
}
