// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: repos.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (
        id,
        name,
        user_id,
        star_gazers,
        watchers,
        url,
        repo_created_at,
        repo_updated_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
RETURNING id
`

type CreateRepoParams struct {
	ID            uuid.UUID
	Name          string
	UserID        uuid.UUID
	StarGazers    int32
	Watchers      int32
	Url           string
	RepoCreatedAt time.Time
	RepoUpdatedAt time.Time
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createRepo,
		arg.ID,
		arg.Name,
		arg.UserID,
		arg.StarGazers,
		arg.Watchers,
		arg.Url,
		arg.RepoCreatedAt,
		arg.RepoUpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
