// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: repos_languages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRepoLanguage = `-- name: CreateRepoLanguage :exec
INSERT INTO repos_languages (
        id,
        repo_id,
        language_id,
        bytes
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
`

type CreateRepoLanguageParams struct {
	ID         uuid.UUID
	RepoID     uuid.UUID
	LanguageID uuid.UUID
	Bytes      int32
}

func (q *Queries) CreateRepoLanguage(ctx context.Context, arg CreateRepoLanguageParams) error {
	_, err := q.db.ExecContext(ctx, createRepoLanguage,
		arg.ID,
		arg.RepoID,
		arg.LanguageID,
		arg.Bytes,
	)
	return err
}
